language: python

cache: pip

os:
  - linux

python:
  - 3.6
  - 3.8

before_install:
  # Strangely enough numpy is already installed on Travis's VMs
  - pip install -r requirements-dev.txt

install:
  - pip install -e .

script:
  - pytest -xvv tests
  - safety check
